apiVersion: v1
kind: Service
metadata:
  name: alpine-svc
spec:
  ports:
  - port: 12345
    name: test
  selector:
    app: alpine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deploy
  labels:
    app: alpine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine
        image: alpine
        imagePullPolicy: IfNotPresent
        tty: true

      nodeSelector:
        beta.kubernetes.io/arch: amd64
