version: '3.4'

services:
    hub:
        image: selenium/hub
        container_name: hub
        ports:
          - "4444:4444"
        
        healthcheck:
          test: ["CMD", "curl", "-f", "http://192.168.128.3:4444/wd/hub"]
          interval: 30s
          timeout: 10s
          retries: 5

        networks:
            forex:
                ipv4_address: 172.28.0.22

        command: /opt/bin/entry_point.sh

    chrome:
        image: selenium/node-chrome
        container_name: chrome
        environment:
          - HUB_HOST=hub
          - HUB_PORT=4444
        
        volumes:
          - /dev/shm:/dev/shm
          - ".:/workspace/:z"
        user: root
        networks:
            forex:
                ipv4_address: 172.28.0.23
        
    forex:
        image: amancevice/pandas
        build: .
        volumes:
          - "/tmp/.X11-unix:/tmp/.X11-unix"
          - ".:/workspace/:z"
          - /dev/shm:/dev/shm
        user: root
        environment:
          - "DISPLAY=$DISPLAY"
          - "QT_X11_NO_MITSHM=1"
          - HUB_HOST=hub
          - HUB_PORT=4444
          
        working_dir: /workspace
        networks:
            forex:
        
        tty: true
        command: bash

    visual:
        image: jupyter/scipy-notebook
        container_name: visual
        hostname: visual
        ports:
          - "8888:8888"
        user: root
        networks:
          - forex
        volumes:
          - "/tmp/.X11-unix:/tmp/.X11-unix"
          - ".:/workspace:z"
        working_dir: /workspace
        environment:
          - "DISPLAY=$DISPLAY"
          - "QT_X11_NO_MITSHM=1"
          - "NB_UID=1000"

        command: start-notebook.sh

    pytorch:
        build:
          context: .
          dockerfile: ./pytorch_dockerfile
        image: pytorch/pytorch
        container_name: pytorch
        hostname: pytorch        
        user: root   
        volumes:
          - "/tmp/.X11-unix:/tmp/.X11-unix"
          - ".:/workspace/:z"
          #- "./data/:/home/jovyan/Heika/data/:z"
        environment:
          - "DISPLAY=$DISPLAY"
          - "QT_X11_NO_MITSHM=1"
          #- "NB_UID=1000"
        tty: true
        command: bash

  
networks:
  forex:
    ipam:
      driver: default
      config:
        - subnet: "172.28.0.0/16"

